server:
  port: 8112
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
#  instance:
#    instance-id: ${spring.application.name}-${random.int}
#    hostname: localhost
spring:
  application:
    name: PRODUCT-SERVICES
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/akpolDB?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
akpol:
  account-base-url: http://localhost:8111
  api:
    member: /api/member
    member-name: /api/member/name